name: balcony
description: "workspaces,a change in scenery,property rentals"
.publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.0
  hive: ^2.2.3
  logger: ^2.4.0
  path_provider: ^2.1.4
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  intl:
  intl_utils: ^2.8.7
  cached_network_image: ^3.4.1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.0.0
  form_field_validator: ^1.1.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  connectivity_plus: ^6.1.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1
  mobx_codegen: ^2.6.0+1
  # API generator
  retrofit_generator: ^8.0.6

  # json parsing
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:


  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
  assets:
    - assets/images/
    - assets/
    - assets/dummy/
    - assets/fonts/



flutter_intl: true


flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: generated
  # Optional. Sets whether utomatic monitoring of file changes. Default: true
  auto_detection: true
  # Optional. Sets file name conversion rules. Default: true
  named_with_parent: true
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: assets
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: Assets
  # Optional. Sets the filename split pattern for filename split. Default: [-_]
  filename_split_pattern: "[-_]"
  # Optional. Configuring ignore paths. Default: [],e.g: ["assets/fonts", "assets/images/dark", ...]
  path_ignore: []