name: balcony
description: "workspaces,a change in scenery,property rentals"
.publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.0
  hive: ^2.2.3
  logger: ^2.4.0
  path_provider: ^2.1.4
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  intl:
  intl_utils: ^2.8.7


dev_dependencies:
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:


  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Black.otf
          weight: 900


flutter_intl: true